### ISSUE TITLE
That's not how regex is

### ISSUE THREAD

**Issue by colinta** [crossroadlabs/Regex#28]
Your README is full of examples of `[1,2,3]`, but character classes do not use commas.  So either you _really want to match commas_, or your README needs to be remedied. :smiley:

(should be just `[123]`)

**Comment by dileping** [comment]
@colinta Thanks for pointing! Would you like to make a PR?

**Comment by natebird** [comment]
I was going to make a pull request to update the readme but the project requires signing a CLA to contribute. No thanks.

**Comment by dileping** [comment]
@natebird What is your concern with the CLA?

**Comment by colinta** [comment]
Nice, thanks for fixing that!

**Comment by dileping** [comment]
@colinta Welcome ;)
