### ISSUE TITLE
Error in dependencies

### ISSUE THREAD

**Issue by califrench** [crossroadlabs/Regex#29]
When I try importing Regex with the following dependency in my project, I'm getting different contents for the `Package.swift` file:

``` swift
//In my own Package.swift file
    ...
    .Package(url: "https://github.com/crossroadlabs/Regex.git", majorVersion: 0),
    ...
```

Contents of the `Regex`/`Package.swift` I'm getting:

``` swift
import PackageDescription

let package = Package(
    name: "Regex",
    targets: [Target(name: "Regex")],
    dependencies: [.Package(url: "https://github.com/crossroadlabs/Boilerplate.git", majorVersion: 0, minor: 2)]
)
```

Instead of

``` swift
import PackageDescription

let package = Package(
    name: "Regex",
    targets: [Target(name: "Regex")],
    dependencies: [.Package(url: "https://github.com/crossroadlabs/Boilerplate.git", Version(1, 0, 0, prereleaseIdentifiers: ["alpha", "1"]))],
    exclude: ["Carthage"]
)
```

What's odd is that SPM is resolving Regex 0.8.0 but with different contents than this repo.
The issue is that Boilerplate depends on Result and they have both been updated to support Swift 3, but the version of Regex I'm getting is relying on a deprecated version of Boilerplate.

**Comment by dileping** [comment]
@califrench Try to use new version 1.0.0-alpha.1 which supports Swift 3.0 and has no Boilerplate dependency.
