### ISSUE TITLE
Error on swift build

### ISSUE THREAD

**Issue by frranck** [crossroadlabs/Regex#33]
Hello;
I've got this error on both Mac OS X and Linux when trying to use crossroadlabs/Regex:

error: the module at Tests/Result has an invalid name ('Result'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/Result’ to have a ‘Tests’ suffix

**Comment by revolter** [comment]
How did you solve it?

**Comment by frranck** [comment]
Can't remember, but It somehow worked using it in this project: https://github.com/frranck/asm2c
