### ISSUE TITLE
RegEx not matched due to extended Unicode characters

### ISSUE THREAD

**Issue by kapfab** [crossroadlabs/Regex#38]
When a string contains extended Unicode characters (like emojis), RegEx are not applied to its entirety.
This is usually unnoticed but when you try to match something at the very end of a string containing emojis, you can spend hours trying to find an issue in your RegEx…

This is probably linked to the NSString/String mapping used for Swift RegEx functions, explained here:
https://stackoverflow.com/questions/29756530/swift-regex-matching-fails-when-source-contains-unicode-characters

Replacing the few occurrences of
```swift
    let range = GroupRange(location: 0, length: source.characters.count)
```
by
```swift
    let range = GroupRange(location: 0, length: (source as NSString).length)
```
seems to make everything working fine.

**Comment by kengruven** [comment]
My understanding is that `.characters` (a String.CharacterView) is extended grapheme clusters, while NSRegularExpression expects an NSRange in terms of UTF-16 code units.

Using `source.utf16.count` should also work.

**Comment by ypopovych** [comment]
Should be fixed now
