### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by jacob-greenfield** [crossroadlabs/Regex#43]
Looks like you forgot to run `pod trunk push` on the version bump, it's not showing up:

```
$ pod trunk info CrossroadRegex

CrossroadRegex
    - Versions:
      - 0.3 (2016-01-24 23:51:25 UTC)
      - 0.4 (2016-01-25 16:37:05 UTC)
      - 0.4.1 (2016-02-09 17:47:28 UTC)
      - 0.5 (2016-02-18 10:30:15 UTC)
      - 0.5.2 (2016-02-18 11:32:27 UTC)
      - 0.6.0 (2016-04-06 11:29:12 UTC)
      - 0.7.0 (2016-06-18 19:31:02 UTC)
      - 0.8.0 (2016-07-28 18:40:03 UTC)
      - 1.0.0 (2017-04-15 13:47:51 UTC)
      - 1.0.0-alpha.1 (2016-11-04 18:51:05 UTC)
    - Owners:
      - Daniel Leping <dileping@gmail.com>
```

**Comment by Coder-256** [comment]
Whoops nevermind :flushed:

**Comment by Coder-256** [comment]
Didn't mean to close, this is still an issue! Just run `pod trunk push` in the repo.

**Comment by jacob-greenfield** [comment]
@dileping Could you please run `pod trunk push` so that the pod works in the newest version?

**Comment by jacob-greenfield** [comment]
I hate to bug you but v1.1 is *still* not working...

**Comment by lynchsft** [comment]
Same. Really want to be using v1.1. Stuck on 1.0 right now because of the state of the pod. :/

**Comment by jacob-greenfield** [comment]
@lynchrb For the time being, we can use: `pod "CrossroadRegex", :git => "https://github.com/CrossroadLabs/Regex.git", :tag => "1.1.0"` but this is not a long-term solution (for example, `pod update` doesn't do anything, compared to using `pod "CrossroadRegex", "~> 1.1.0"`).

**Comment by jacob-greenfield** [comment]
Never mind, they just updated the version today!

**Comment by dileping** [comment]
@Coder-256, @lynchrb: guys, thank you for your patience.
